### ISSUE TITLE
Possible to document installation of emotion.so to naoqi

### ISSUE THREAD

**Issue by svenwoldt** [davesnowdon/nao-emotional-framework#21]
Hello,
could you please elaborate a little bit on what I have to do to integrate and use the emotion module in naoqi? 
So I can actually run EmotionalTTS as described in config.py in a project?
I have qibuild installed but don't know what to do really, tried some things but I feel stupid.
Some help would be greatly appreciated.
Many thanks,
Sven

**Comment by davesnowdon** [comment]
I've added a section to the README that describes how to build and run the project
